api:
  image:
    repository: ghcr.io/layari/crud-app-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001

view:
  image:
    repository: ghcr.io/layari/crud-app-view
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5173

mysql:
  enabled: true
  auth:
    rootPassword: rootpassword
    database: mydb
    username: myuser
    password: mypassword
  primary:
    image:
      repository: mysql
      tag: "8"
      pullPolicy: IfNotPresent
    service:
      port: 3306


