apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-app.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "crud-app.name" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "crud-app.name" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: {{ include "crud-app.fullname" . }}-mysql
            - name: DB_USER
              value: {{ .Values.mysql.user }}
            - name: DB_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: DB_NAME
              value: {{ .Values.mysql.database }}